name: plants_repository
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/tolland/ui_challenge/tree/develop/packages/plants_repository

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  json_annotation: ^4.6.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
